=== jvelarde94/nyc-xml/index.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
   XML Final
   Transportation in NYC
   Author: Jeremy Velarde
   Date:   11/21/2016
   File: index.xsd
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://example.com/final/index"
	targetNamespace="http://example.com/final/index"
	elementFormDefault="qualified">

	<xs:element name="title" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:attribute name="src" type="srcType" />

	<xs:element name="index">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="home"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="home">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="description"/>
				<xs:element ref="images" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="images">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="img" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="img">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="src" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== jvelarde94/nyc-xml/index.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
   XML Final
   Transportation in NYC
   Author: Jeremy Velarde
   Date:   11/21/2016
   File: index.xml
-->
<?xml-stylesheet type="text/xsl" href="index.xsl" ?>

<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:indx="http://example.com/final/index"
	xsi:schemaLocation="http://example.com/final/index index.xsd">

	<home>
		<title> TRAVEL NYC </title>
		<description> 
			Find popular locations and pricing in New York City. 
		</description>
		<images>
			<img src="images/statueofliberty.jpg" width="400" height="200" />
			<img src="images/centralpark.jpg" width="400" height="200"/>
			<img src="images/halal.jpg" width="400" height="200" />
			<img src="images/empirestatebuilding.jpg" width="400" height="200" />
			<img src="images/moma.jpg" width="400" height="200" />
			<img src="images/wtc.jpg" width="400" height="200" />
			<img src="images/timessquare.jpg" width="400" height="200" />
			<img src="images/gz.jpg" width="400" height="200" />
		</images>
	</home>

</index>
