=== jvelarde94/nyc-xml/pricing.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
   XML Final
   Transportation in NYC
   Author: Jeremy Velarde
   Date:   11/21/2016
   File: pricing.xsd
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://example.com/final/pricing"
	targetNamespace="http://example.com/final/pricing"
	elementFormDefault="qualified">

	<xs:element name="title" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="sName" type="xs:string"/>
	<xs:element name="sCost" type="xs:string"/>
	<xs:element name="hName" type="xs:string"/>
	<xs:element name="hCost" type="xs:string"/>
	<xs:element name="hRating" type="xs:string"/>
	<xs:element name="nearRestaurant" type="xs:string"/>
	<xs:element name="pubTravel" type="xs:string"/>
	<xs:element name="priTravel" type="xs:string"/>
	<xs:attribute name="src" type="srcType" />

	<xs:element name="pricings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pricingInfo"/>
				<xs:element name="pricing" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="pricingInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="description"/>
				</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="pricing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="spot"/>
				<xs:element ref="hotel"/>
				<xs:element ref="nearRestaurant"/>
				<xs:element ref="pubTravel"/>
				<xs:element ref="priTravel" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="spot">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sName"/>
				<xs:element ref="sCost"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hotel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hName"/>
				<xs:element ref="hCost"/>
				<xs:element ref="hRating"/>
				<xs:element ref="hImage" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hImage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="img" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="img">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="src" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jvelarde94/nyc-xml/pricing.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
   XML Final
   Transportation in NYC
   Author: Jeremy Velarde
   Date:   11/21/2016
   File: prices.xml
-->
<?xml-stylesheet type="text/xsl" href="pricing.xsl" ?>

<pricings xmlns:xsi="http://www.w3.org/4001/XMLSchema-instance"
	xmlns:prc="http://example.com/final/pricing"
	xsi:schemaLocation="http://example.com/final/pricing pricing.xsd">

	<pricingInfo>
		<title> PRICING </title>
		<description> Hotel Pricing and Admission Fees </description>
	</pricingInfo>

	<pricing>
		<spot>
			<sName>Musem of Modern Art</sName>
			<sCost>25</sCost>
		</spot>
		<hotel>
			<hName>Warwick New York</hName>
			<hCost>206</hCost>
			<hRating>4.3</hRating>
			<hImage>
				<img src="images/warwickHotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>Connolly's Pub and Restaurant</nearRestaurant>
		<pubTravel>Bus, Subway</pubTravel>
		<priTravel>CitiBike, Taxi, Uber, Walk</priTravel>
	</pricing>
	
	<pricing>
		<spot>
			<sName>Times Square</sName>
			<sCost>Free</sCost>
		</spot>
		<hotel>
			<hName>Renaissance New York Times Square Hotel</hName>
			<hCost>239</hCost>
			<hRating>4.2</hRating>
			<hImage>
				<img src="images/renaissanceHotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>Langan's Pub and Restaurant</nearRestaurant>
		<pubTravel>Bus, Subway</pubTravel>
		<priTravel>CitiBike, Taxi, Uber, Walk</priTravel>
	</pricing>
	
	<pricing>
		<spot>
			<sName>Central Park</sName>
			<sCost>Free</sCost>
		</spot>
		<hotel>
			<hName>Park Lane Hotel New York</hName>
			<hCost>299</hCost>
			<hRating>3.8</hRating>
			<hImage>
				<img src="images/parklaneHotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>The Plaza Food Hall</nearRestaurant>
		<pubTravel>Bus, Subway</pubTravel>
		<priTravel>CitiBike, Taxi, Uber, Walk</priTravel>
	</pricing>
	
	<pricing>
		<spot>
			<sName>World Trade Center</sName>
			<sCost>28</sCost>
		</spot>
		<hotel>
			<hName>World Center Hotel</hName>
			<hCost>152</hCost>
			<hRating>4.3</hRating>
			<hImage>
				<img src="images/worldcenterHotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>Bill's Bar and Burger</nearRestaurant>
		<pubTravel>Bus, Subway</pubTravel>
		<priTravel>CitiBike, Taxi, Uber, Walk</priTravel>
	</pricing>
	
	<pricing>
		<spot>
			<sName>Empire State Building</sName>
			<sCost>34</sCost>
		</spot>
		<hotel>
			<hName>Hotel 373 Fifth Avenue</hName>
			<hCost>99</hCost>
			<hRating>3.8</hRating>
			<hImage>
				<img src="images/373Hotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>STATE Bar and Grill</nearRestaurant>
		<pubTravel>Bus, Subway</pubTravel>
		<priTravel>CitiBike, Taxi, Uber, Walk</priTravel>
	</pricing>

	<pricing>
		<spot>
			<sName>Statue of Liberty</sName>
			<sCost>18</sCost>
		</spot>
		<hotel>
			<hName>DoubleTree by Hilton Hotel NYC Financial District</hName>
			<hCost>143</hCost>
			<hRating>3.8</hRating>
			<hImage>
				<img src="images/doubletreeHotel.jpg" width="600" height="400"/>
			</hImage>
		</hotel>
		<nearRestaurant>The Dead Rabbit</nearRestaurant>
		<pubTravel>Ferry</pubTravel>
	</pricing>
	
</pricings>
